# roles/secrets/tasks/main.yml
---
- block:
    - name: Export decrypted secrets
      ansible.builtin.copy:
        dest: "{{ secrets_tmp_file }}"
        mode: 0640
        force: yes
        content: "{{ secrets_vars }}"
  rescue:
    - name: Remove secrets tmp file
      ansible.builtin.file:
        dest: "{{ secrets_tmp_file }}"
        state: absent
      failed_when: false
