version: 2

updates:
  - package-ecosystem: github-actions
    target-branch: dev
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
