# install.yml
#
# This playbook installs dotfiles.
---
- name: Install dotfiles
  hosts: devbox
  vars:
    dotfiles_install: true
  vars_files:
    - roles/homebrew/defaults/main.yml
    - roles/macports/defaults/main.yml
  roles:
    - ssh
    - config
    - env
    - shell
