# uninstall.yml
#
# This playbook uninstalls dotfiles.
---
- name: Uninstall dotfiles
  hosts: devbox
  vars:
    dotfiles_install: false
  vars_files:
    - roles/homebrew/defaults/main.yml
    - roles/macports/defaults/main.yml
    - roles/node/defaults/main.yml
  roles:
    - ssh
    - config
    - env
    - shell
    - util
