# secrets.yml
#
# This playbook updates the dotfiles repository.
---
- name: Update dotfiles
  hosts: devbox
  tasks:
    - name: Update repository
      ansible.builtin.git:
        repo: "{{ dotfiles_repository }}"
        dest: "{{ dotfiles_dir }}"
        clone: false
        update: yes
      register: dotfiles_repo
