# roles/macports/tasks/main.yml
---
- name: Override installed ports
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop: "{{ macports_overrides }}"
  loop_control:
    label: "{{ item.src }}"

- block:
    - name: Update Macports
      community.general.macports:
        selfupdate: true

    - name: Remove abandoned ports
      ansible.builtin.command: port uninstall --follow-dependencies installed and {{ item.port }}
      loop: "{{ macports_ports_abandoned }}"
      loop_control:
        label: "{{ item.port }}"

    - name: Upgrade installed ports
      community.general.macports:
        upgrade: true

    - name: Install ports
      community.general.macports:
        name: "{{ item.port }}"
        variant: "{{ item.variant | default(None) }}"
        state: present
      loop: "{{ macports_ports }}"
      loop_control:
        label: "{{ item.port }}"

    - name: Mark installed ports requested
      ansible.builtin.command: port setrequested {{ item.port }}
      loop: "{{ macports_ports }}"
      loop_control:
        label: "{{ item.port }}"

    - name: Activate ports
      community.general.macports:
        name: "{{ item.port }}"
        state: active
      loop: "{{ macports_ports }}"
      loop_control:
        label: "{{ item.port }}"

    - name: Select default ports
      ansible.builtin.command: port -N select --set {{ item.program }} {{ item.binary }}
      loop: "{{ macports_ports_select }}"
      loop_control:
        label: "{{ item.program }}"

    - name: Manually select default ports
      ansible.builtin.file:
        src: "{{ macports_bin }}/{{ item.binary }}"
        dest: "{{ macports_bin }}/{{ item.program }}"
        owner: root
        group: admin
        state: link
      loop: "{{ macports_ports_select_manual }}"
      loop_control:
        label: "{{ item.program }}"
  become: true
