# group_vars/devbox/config_vars.yml
---
config_git_account_lojoja:
  signing_ids: "{{ vault_config_git_account_lojoja_signing_ids }}"
  signing_keys:
    - "{{ ssh_key_lojoja_ed25519 }}"
    - "{{ ssh_key_lojoja_remote }}"
  user_email: "{{ vault_config_git_account_lojoja_user_email }}"
  user_name: "{{ vault_config_git_account_lojoja_user_name }}"
  user_key: "{{ ssh_key_lojoja_ed25519 }}"
  user_remote_key: "{{ ssh_key_lojoja_remote }}"

config_git_account_snldev:
  signing_ids: "{{ vault_config_git_account_snldev_signing_ids }}"
  signing_keys:
    - "{{ ssh_key_snldev_ed25519 }}"
    - "{{ ssh_key_snldev_remote }}"
  user_email: "{{ vault_config_git_account_snldev_user_email }}"
  user_name: "{{ vault_config_git_account_snldev_user_name }}"
  user_key: "{{ ssh_key_snldev_ed25519 }}"
  user_key_remote: "{{ ssh_key_snldev_remote }}"
