# roles/homebrew/tasks/main.yml
---
- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Remove abandoned formulae
  community.general.homebrew:
    name: "{{ item }}"
    state: absent
  loop: "{{ homebrew_formulae_abandoned }}"

- name: Remove abandoned taps
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: absent
  loop: "{{ homebrew_taps_abandoned }}"

- name: Upgrade installed formulae
  community.general.homebrew:
    upgrade_all: true

- name: Install taps
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_taps }}"

- name: Install formulae
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_formulae }}"

- name: Install casks
  community.general.homebrew_cask:
    name: "{{ item.name }}"
    state: present
    options: "{{ item.options | default }}"
  loop: "{{ homebrew_casks }}"
