# dotfiles/shared/shell/custom/poetry.sh
# shellcheck shell=bash

if hash poetry &>/dev/null
then
  export POETRY_CACHE_DIR="$HOME/Library/Caches/pypoetry"
  export POETRY_CONFIG_DIR="$DOTFILES_INSTALLED_CONFIG_PATH/poetry"
  export POETRY_CONFIG_FILE="$POETRY_CONFIG_DIR/config.toml"
  export POETRY_REPOSITORIES_LOJOJA_URL="$GITEA_PYPI_PACKAGE_REPO_LOJOJA"
  export POETRY_REPOSITORIES_SNLDEV_URL="$GITEA_PYPI_PACKAGE_REPO_SNLDEV"
  export POETRY_CERTIFICATES_LOJOJA_CERT="$LOJOJA_CA_CERTS"
  export POETRY_CERTIFICATES_SNLDEV_CERT="$LOJOJA_CA_CERTS"
fi
