# roles/config/tasks/install.yml
---
- name: Clean abandoned config
  ansible.builtin.file:
    dest: "{{ item }}"
    state: absent
  loop: "{{ config_abandoned }}"

- name: Create config directories
  ansible.builtin.file:
    dest: "{{ item }}"
    mode: 0755
    state: directory
  loop: "{{ config_dirs }}"

- name: Add .hushlogin
  ansible.builtin.copy:
    dest: "{{ config_hushlogin }}"
    mode: 0644
    force: no
    content: ""

- name: Add config files
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "{{ item.file }}"
    mode: 0644
  loop: "{{ config_templates }}"
  loop_control:
    label: "{{ item.file }}"

- name: Add Google credentials
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ config_google_dir }}/{{ item }}"
    mode: 0644
  loop: "{{ config_google_credentials }}"
  loop_control:
    label: "{{ item }}"

- name: Add iterm2 profiles
  ansible.builtin.template:
    src: iterm2_theme.j2
    dest: "{{ config_iterm2_dir }}/{{ item.name }}.json"
    mode: 0644
  loop: "{{ config_iterm2_profiles }}"
  loop_control:
    label: "{{ item.name }}"

- name: Add ssl certificates
  ansible.builtin.copy:
    src: "{{ item.file }}"
    dest: "{{ config_ssl_dir }}/{{ item.file }}"
    mode: 0644
  loop: "{{ config_ssl_ca_certs + config_ssl_ca_chain_certs }}"
  loop_control:
    label: "{{ item.file }}"

- name: Identify new trusted CA certificates
  ansible.builtin.command: security verify-cert -c "{{ config_ssl_dir }}/{{ item.file }}"
  register: new_ca_cert_cmd
  changed_when: false
  failed_when: new_ca_cert_cmd.rc > 1
  loop: "{{ config_ssl_ca_certs }}"
  loop_control:
    label: "{{ item.file }}"

- name: Install trusted CA certificates
  ansible.builtin.command: security add-trusted-cert -d -r {{ item.item.root | ternary("trustRoot", "trustAsRoot") }} -k /Library/Keychains/System.keychain "{{ config_ssl_dir }}/{{ item.item.file }}"
  when: item.rc == 1
  loop: "{{ new_ca_cert_cmd.results }}"
  loop_control:
    label: "{{ item.item.file }}"
  become: true

- name: Add ssl identity certificates
  ansible.builtin.copy:
    src: "{{ item.file }}"
    dest: "{{ config_ssl_dir }}/{{ item.file }}"
    mode: 0644
  loop: "{{ config_ssl_identity_certs }}"
  loop_control:
    label: "{{ item.file }}"

- name: Import ssl identity certificates
  ansible.builtin.command: security import "{{ config_ssl_dir }}/{{ item.file }}" -P {{ item.passphrase }}
  loop: "{{ config_ssl_identity_certs }}"
  loop_control:
    label: "{{ item.file }}"
