# roles/config/tasks/install.yml
---
- name: Create config directories
  ansible.builtin.file:
    dest: "{{ item }}"
    mode: 0755
    state: directory
  loop: "{{ config_dirs }}"

- name: Add .hushlogin
  ansible.builtin.copy:
    dest: "{{ config_hushlogin }}"
    mode: 0644
    force: no
    content: ""

- name: Add config files
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "{{ item.file }}"
    mode: 0644
  loop: "{{ config_templates }}"
  loop_control:
    label: "{{ item.file }}"

- name: Add ssl certificates
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ config_ssl_dir }}/{{ item }}"
    mode: 0644
  loop: "{{ config_ssl_certs + config_ssl_root_certs + config_ssl_intermediate_certs }}"

- block:
    - name: Change trust-root security permissions
      ansible.builtin.shell: security authorizationdb write com.apple.trust-settings.admin < {{ config_ssl_permissions_ansible }}

    - name: Install trusted root certificates
      ansible.builtin.command: security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain "{{ config_ssl_dir }}/{{ item }}"
      loop: "{{ config_ssl_root_certs }}"

    - name: Install trusted intermediate certificates
      ansible.builtin.command: security add-trusted-cert -d -r trustAsRoot -k /Library/Keychains/System.keychain "{{ config_ssl_dir }}/{{ item }}"
      loop: "{{ config_ssl_intermediate_certs }}"
  always:
    - name: Reset trust-root security permissions
      ansible.builtin.shell: security authorizationdb write com.apple.trust-settings.admin < {{ config_ssl_permissions_default }}
  become: yes

- name: Add ssl client certificates
  ansible.builtin.copy:
    src: "{{ item.file }}"
    dest: "{{ config_ssl_dir }}/{{ item.file }}"
    mode: 0644
  loop: "{{ config_ssl_client_certs }}"
  loop_control:
    label: "{{ item.file }}"

- name: Import ssl client certificates
  ansible.builtin.command: security import "{{ config_ssl_dir }}/{{ item.file }}" -P {{ item.passphrase }}
  loop: "{{ config_ssl_client_certs }}"
  loop_control:
    label: "{{ item.file }}"
