# roles/util/defaults/main.yml
---
util_shell_scripts:
  - file: git-sops
    template: git-sops.j2

util_python_all: "{{ util_python_public + util_python_private }}"

util_python_public:
  - name: py-service
    cmd: service
    python_version: 3.11
  - name: py-triex
    cmd: triex
    python_version: 3.11
  - name: py-wake-cli
    cmd: wake
    python_version: 3.11

util_python_private:
  - name: clientfile
    cmd: clientfile
    python_version: 3.11
    owner: snldev
    repo: clientfile
