# roles/secrets/defaults/main.yml
---
secrets_search_pattern: ^vault_env_.+$
secrets_varnames: "{{ query('ansible.builtin.varnames', secrets_search_pattern) }}"
secrets_vars: "{{ dict(secrets_varnames | zip(query('ansible.builtin.vars', *secrets_varnames))) | to_nice_yaml }}"
secrets_tmp_file: /tmp/dotfiles-secrets
