# roles/ssh/defaults/main/vars.yml
---
ssh_dir: "{{ dotfiles_install_base_dir }}/.ssh"

ssh_host_default_identities: []

ssh_host_er_6p_public_keys: "{{ vault_ssh_host_er_6p_public_keys }}"
ssh_host_er_6p_user: "{{ vault_ssh_host_er_6p_user }}"

ssh_host_es48_500w_1_public_keys: "{{ vault_ssh_host_es48_500w_1_public_keys }}"
ssh_host_es48_500w_1_user: "{{ vault_ssh_host_es48_500w_1_user }}"

ssh_host_es48_500w_2_public_keys: "{{ vault_ssh_host_es48_500w_2_public_keys }}"
ssh_host_es48_500w_2_user: "{{ vault_ssh_host_es48_500w_2_user }}"

ssh_host_es48_lite_public_keys: "{{ vault_ssh_host_es48_lite_public_keys }}"
ssh_host_es48_lite_user: "{{ vault_ssh_host_es48_lite_user }}"

ssh_host_es24_250w_public_keys: "{{ vault_ssh_host_es24_250w_public_keys }}"
ssh_host_es24_250w_user: "{{ vault_ssh_host_es24_250w_user }}"

ssh_host_unbound_public_keys: "{{ vault_ssh_host_unbound_public_keys }}"
ssh_host_unbound_user: "{{ vault_ssh_host_unbound_user }}"

ssh_host_pihole_public_keys: "{{ vault_ssh_host_pihole_public_keys }}"
ssh_host_pihole_user: "{{ vault_ssh_host_pihole_user }}"

ssh_host_pve_public_keys: "{{ vault_ssh_host_pve_public_keys }}"
ssh_host_pve_user: "{{ vault_ssh_host_pve_user }}"

ssh_host_ds923p_public_keys: "{{ vault_ssh_host_ds923p_public_keys }}"
ssh_host_ds923p_user: "{{ vault_ssh_host_ds923p_user }}"

ssh_host_ds220j_public_keys: "{{ vault_ssh_host_ds220j_public_keys }}"
ssh_host_ds220j_user: "{{ vault_ssh_host_ds220j_user }}"

ssh_host_caddy_public_keys: "{{ vault_ssh_host_caddy_public_keys }}"
ssh_host_caddy_user: "{{ vault_ssh_host_caddy_user }}"

ssh_host_postgres_public_keys: "{{ vault_ssh_host_postgres_public_keys }}"
ssh_host_postgres_user: "{{ vault_ssh_host_postgres_user }}"

ssh_host_victoria_public_keys: "{{ vault_ssh_host_victoria_public_keys }}"
ssh_host_victoria_user: "{{ vault_ssh_host_victoria_user }}"

ssh_host_hass_public_keys: "{{ vault_ssh_host_hass_public_keys }}"
ssh_host_hass_user: "{{ vault_ssh_host_hass_user }}"

ssh_host_jellyfin_public_keys: "{{ vault_ssh_host_jellyfin_public_keys }}"
ssh_host_jellyfin_user: "{{ vault_ssh_host_jellyfin_user }}"

ssh_host_stash_public_keys: "{{ vault_ssh_host_stash_public_keys }}"
ssh_host_stash_user: "{{ vault_ssh_host_stash_user }}"

ssh_host_sabnzbd_public_keys: "{{ vault_ssh_host_sabnzbd_public_keys }}"
ssh_host_sabnzbd_user: "{{ vault_ssh_host_sabnzbd_user }}"

ssh_host_wireguard_public_keys: "{{ vault_ssh_host_wireguard_public_keys }}"
ssh_host_wireguard_user: "{{ vault_ssh_host_wireguard_user }}"

ssh_host_qbit_public_keys: "{{ vault_ssh_host_qbit_public_keys }}"
ssh_host_qbit_user: "{{ vault_ssh_host_qbit_user }}"

ssh_host_radarr_public_keys: "{{ vault_ssh_host_radarr_public_keys }}"
ssh_host_radarr_user: "{{ vault_ssh_host_radarr_user }}"

ssh_host_sonarr_public_keys: "{{ vault_ssh_host_sonarr_public_keys }}"
ssh_host_sonarr_user: "{{ vault_ssh_host_sonarr_user }}"

ssh_host_whisparr_public_keys: "{{ vault_ssh_host_whisparr_public_keys }}"
ssh_host_whisparr_user: "{{ vault_ssh_host_whisparr_user }}"

ssh_host_prowlarr_public_keys: "{{ vault_ssh_host_prowlarr_public_keys }}"
ssh_host_prowlarr_user: "{{ vault_ssh_host_prowlarr_user }}"

ssh_host_configarr_public_keys: "{{ vault_ssh_host_configarr_public_keys }}"
ssh_host_configarr_user: "{{ vault_ssh_host_configarr_user }}"

ssh_host_flaresolverr_public_keys: "{{ vault_ssh_host_flaresolverr_public_keys }}"
ssh_host_flaresolverr_user: "{{ vault_ssh_host_flaresolverr_user }}"

ssh_host_byparr_public_keys: "{{ vault_ssh_host_byparr_public_keys }}"
ssh_host_byparr_user: "{{ vault_ssh_host_byparr_user }}"

ssh_host_bazarr_public_keys: "{{ vault_ssh_host_bazarr_public_keys }}"
ssh_host_bazarr_user: "{{ vault_ssh_host_bazarr_user }}"

ssh_host_github_alt_identities: []
ssh_host_github_alt_suffix: alt
ssh_host_github_public_keys: "{{ vault_ssh_host_github_public_keys }}"
ssh_host_github_user: "{{ vault_ssh_host_github_user }}"

ssh_hosts:
  - name: LAN
    hosts:
      - hostname: er-6p.internal
        hosts:
          - er-6p
          - er-6p.internal
          - router
          - router.internal
        ip: 192.168.1.1
        public_keys: "{{ ssh_host_er_6p_public_keys }}"
        user: "{{ ssh_host_er_6p_user }}"
      - hostname: es48-500w-1.internal
        hosts:
          - es48-500w-1
          - es48-500w-1.internal
          - switch1
          - switch1.internal
        ip: 192.168.1.11
        preferred_authentications: password
        public_keys: "{{ ssh_host_es48_500w_1_public_keys }}"
        user: "{{ ssh_host_es48_500w_1_user }}"
      - hostname: es48-500w-2.internal
        hosts:
          - es48-500w-2
          - es48-500w-2.internal
          - switch2
          - switch2.internal
        ip: 192.168.1.12
        preferred_authentications: password
        public_keys: "{{ ssh_host_es48_500w_2_public_keys }}"
        user: "{{ ssh_host_es48_500w_2_user }}"
      - hostname: es48-lite.internal
        hosts:
          - es48-lite
          - es48-lite.internal
          - switch3
          - switch3.internal
        ip: 192.168.1.13
        preferred_authentications: password
        public_keys: "{{ ssh_host_es48_lite_public_keys }}"
        user: "{{ ssh_host_es48_lite_user }}"
      - hostname: es24-250w.internal
        hosts:
          - es24-250w
          - es24-250w.internal
          - switch4
          - switch4.internal
        ip: 192.168.1.14
        preferred_authentications: password
        public_keys: "{{ ssh_host_es24_250w_public_keys }}"
        user: "{{ ssh_host_es24_250w_user }}"
      - hostname: unbound.internal
        hosts:
          - unbound
          - unbound.internal
        ip: 192.168.20.11
        public_keys: "{{ ssh_host_unbound_public_keys }}"
        user: "{{ ssh_host_unbound_user }}"
      - hostname: pihole.internal
        hosts:
          - pihole
          - pihole.internal
        ip: 192.168.50.12
        public_keys: "{{ ssh_host_pihole_public_keys }}"
        user: "{{ ssh_host_pihole_user }}"
      - hostname: pve.internal
        hosts:
          - pve
          - pve.internal
        ip: 192.168.20.20
        public_keys: "{{ ssh_host_pve_public_keys }}"
        user: "{{ ssh_host_pve_user }}"
      - hostname: ds923p.internal
        hosts:
          - ds923p
          - ds923p.internal
          - nas1
          - nas1.internal
        ip: 192.168.50.21
        public_keys: "{{ ssh_host_ds923p_public_keys }}"
        user: "{{ ssh_host_ds923p_user }}"
      - hostname: ds220j.internal
        hosts:
          - ds220j
          - ds220j.internal
          - nas2
          - nas2.internal
        ip: 192.168.50.22
        public_keys: "{{ ssh_host_ds220j_public_keys }}"
        user: "{{ ssh_host_ds220j_user }}"
      - hostname: caddy.internal
        hosts:
          - caddy
          - caddy.internal
        ip: 192.168.50.50
        public_keys: "{{ ssh_host_caddy_public_keys }}"
        user: "{{ ssh_host_caddy_user }}"
      - hostname: postgres.internal
        hosts:
          - postgres
          - postgres.internal
        ip: 192.168.20.52
        public_keys: "{{ ssh_host_postgres_public_keys }}"
        user: "{{ ssh_host_postgres_user }}"
      - hostname: victoria.internal
        hosts:
          - victoria
          - victoria.internal
        ip: 192.168.20.53
        public_keys: "{{ ssh_host_victoria_public_keys }}"
        user: "{{ ssh_host_victoria_user }}"
      - hostname: hass.internal
        hosts:
          - hass
          - hass.internal
        ip: 192.168.20.54
        public_keys: "{{ ssh_host_hass_public_keys }}"
        user: "{{ ssh_host_hass_user }}"
      - hostname: jellyfin.internal
        hosts:
          - jellyfin
          - jellyfin.internal
        ip: 192.168.20.56
        public_keys: "{{ ssh_host_jellyfin_public_keys }}"
        user: "{{ ssh_host_jellyfin_user }}"
      - hostname: stash.internal
        hosts:
          - stash
          - stash.internal
        ip: 192.168.20.58
        public_keys: "{{ ssh_host_stash_public_keys }}"
        user: "{{ ssh_host_stash_user }}"
      - hostname: sabnzbd.internal
        hosts:
          - sabnzbd
          - sabnzbd.internal
        ip: 192.168.20.59
        public_keys: "{{ ssh_host_sabnzbd_public_keys }}"
        user: "{{ ssh_host_sabnzbd_user }}"
      - hostname: wireguard.internal
        hosts:
          - wireguard
          - wireguard.internal
        ip: 192.168.20.60
        public_keys: "{{ ssh_host_wireguard_public_keys }}"
        user: "{{ ssh_host_wireguard_user }}"
      - hostname: qbittorrent.internal
        hosts:
          - qbit
          - qbit.internal
          - qbittorrent
          - qbittorrent.internal
        ip: 192.168.20.61
        public_keys: "{{ ssh_host_qbit_public_keys }}"
        user: "{{ ssh_host_qbit_user }}"
      - hostname: radarr.internal
        hosts:
          - radarr
          - radarr.internal
        ip: 192.168.20.62
        public_keys: "{{ ssh_host_radarr_public_keys }}"
        user: "{{ ssh_host_radarr_user }}"
      - hostname: sonarr.internal
        hosts:
          - sonarr
          - sonarr.internal
        ip: 192.168.20.63
        public_keys: "{{ ssh_host_sonarr_public_keys }}"
        user: "{{ ssh_host_sonarr_user }}"
      - hostname: whisparr.internal
        hosts:
          - whisparr
          - whisparr.internal
        ip: 192.168.20.64
        public_keys: "{{ ssh_host_whisparr_public_keys }}"
        user: "{{ ssh_host_whisparr_user }}"
      - hostname: prowlarr.internal
        hosts:
          - prowlarr
          - prowlarr.internal
        ip: 192.168.20.65
        public_keys: "{{ ssh_host_prowlarr_public_keys }}"
        user: "{{ ssh_host_prowlarr_user }}"
      - hostname: configarr.internal
        hosts:
          - configarr
          - configarr.internal
        ip: 192.168.20.66
        public_keys: "{{ ssh_host_configarr_public_keys }}"
        user: "{{ ssh_host_configarr_user }}"
      - hostname: flaresolverr.internal
        hosts:
          - flaresolverr
          - flaresolverr.internal
        ip: 192.168.20.67
        public_keys: "{{ ssh_host_flaresolverr_public_keys }}"
        user: "{{ ssh_host_flaresolverr_user }}"
      - hostname: byparr.internal
        hosts:
          - byparr
          - byparr.internal
        ip: 192.168.20.68
        public_keys: "{{ ssh_host_byparr_public_keys }}"
        user: "{{ ssh_host_byparr_user }}"
      - hostname: bazarr.internal
        hosts:
          - bazarr
          - bazarr.internal
        ip: 192.168.20.69
        public_keys: "{{ ssh_host_bazarr_public_keys }}"
        user: "{{ ssh_host_bazarr_user }}"

  - name: Servers
    hosts: []
  - name: Version Control
    hosts:
      - hostname: github.com
        hosts:
          - github-{{ ssh_host_github_alt_suffix }}
        identities: "{{ ssh_host_github_alt_identities }}"
        user: "{{ ssh_host_github_user }}"
      - hostname: github.com
        hosts:
          - github.com
        public_keys: "{{ ssh_host_github_public_keys }}"
        user: "{{ ssh_host_github_user }}"
  - name: Default
    hosts:
      - hosts:
          - "!github-*" # github alt host pattern
        identities: "{{ ssh_host_default_identities }}"
      - hosts:
          - "*"
        add_keys_to_agent: "yes"
        use_keychain: "yes"
        preferred_authentications: publickey
        identities_only: "yes"
        public_key_accepted_algorithms: +ssh-rsa

ssh_keychain_loader_agent_file: com.lojoja.dotfiles.sshLoadKeychain.plist
ssh_keychain_loader_agent: "{{ dotfiles_install_base_dir }}/Library/LaunchAgents/{{ ssh_keychain_loader_agent_file }}"
ssh_keys: []
ssh_keys_remove: []
