# roles/ssh/defaults/main/vars.yml
---
ssh_dir: "{{ dotfiles_install_base_dir }}/.ssh"

ssh_host_bitbucket_alt_identities: []
ssh_host_bitbucket_alt_suffix: alt
ssh_host_bitbucket_public_keys: "{{ vault_ssh_host_bitbucket_public_keys }}"
ssh_host_bitbucket_user: "{{ vault_ssh_host_bitbucket_user }}"

ssh_host_default_identities: []

ssh_host_router_public_keys: "{{ vault_ssh_host_router_public_keys }}"
ssh_host_router_user: "{{ vault_ssh_host_router_user }}"

ssh_host_switch1_public_keys: "{{ vault_ssh_host_switch1_public_keys }}"
ssh_host_switch1_user: "{{ vault_ssh_host_switch1_user }}"

ssh_host_switch2_public_keys: "{{ vault_ssh_host_switch2_public_keys }}"
ssh_host_switch2_user: "{{ vault_ssh_host_switch2_user }}"

ssh_host_github_alt_identities: []
ssh_host_github_alt_suffix: alt
ssh_host_github_public_keys: "{{ vault_ssh_host_github_public_keys }}"
ssh_host_github_user: "{{ vault_ssh_host_github_user }}"

ssh_host_nas_public_keys: "{{ vault_ssh_host_nas_public_keys }}"
ssh_host_nas_user: "{{ vault_ssh_host_nas_user }}"

ssh_host_pve_public_keys: "{{ vault_ssh_host_pve_public_keys }}"
ssh_host_pve_user: "{{ vault_ssh_host_pve_user }}"

ssh_hosts:
  - name: LAN
    hosts:
      - hostname: router.lojoja.com
        hosts:
          - router
          - router.lojoja.com
        ip: 10.1.0.1
        public_keys: "{{ ssh_host_router_public_keys }}"
        user: "{{ ssh_host_router_user }}"
      - hostname: switch1.lojoja.com
        hosts:
          - switch1
          - switch1.lojoja.com
        ip: 10.1.0.10
        preferred_authentications: password
        public_keys: "{{ ssh_host_switch1_public_keys }}"
        user: "{{ ssh_host_switch1_user }}"
      - hostname: switch2.lojoja.com
        hosts:
          - switch2
          - switch2.lojoja.com
        ip: 10.1.0.11
        preferred_authentications: password
        public_keys: "{{ ssh_host_switch2_public_keys }}"
        user: "{{ ssh_host_switch2_user }}"
      - hostname: nas.lojoja.com
        hosts:
          - nas
          - nas.lojoja.com
        ip: 10.3.0.11
        public_keys: "{{ ssh_host_nas_public_keys }}"
        user: "{{ ssh_host_nas_user }}"
      - hostname: pve.lojoja.com
        hosts:
          - pve
          - pve.lojoja.com
        ip: 10.3.0.10
        public_keys: "{{ ssh_host_pve_public_keys }}"
        user: "{{ ssh_host_pve_user }}"
  - name: Servers
    hosts: []
  - name: Version Control
    hosts:
      - hostname: bitbucket.org
        hosts:
          - bitbucket-{{ ssh_host_bitbucket_alt_suffix }}
        identities: "{{ ssh_host_bitbucket_alt_identities }}"
        user: "{{ ssh_host_bitbucket_user }}"
      - hostname: bitbucket.org
        hosts:
          - bitbucket.org
        public_keys: "{{ ssh_host_bitbucket_public_keys }}"
        user: "{{ ssh_host_bitbucket_user }}"
      - hostname: github.com
        hosts:
          - github-{{ ssh_host_github_alt_suffix }}
        identities: "{{ ssh_host_github_alt_identities }}"
        user: "{{ ssh_host_github_user }}"
      - hostname: github.com
        hosts:
          - github.com
        public_keys: "{{ ssh_host_github_public_keys }}"
        user: "{{ ssh_host_github_user }}"

  - name: Default
    hosts:
      - hosts:
          - "!bitbucket-*" # bitbucket alt host pattern
          - "!github-*" # github alt host pattern
        identities: "{{ ssh_host_default_identities }}"
      - hosts:
          - "*"
        add_keys_to_agent: "yes"
        use_keychain: "yes"
        preferred_authentications: publickey
        identities_only: "yes"
        public_key_accepted_algorithms: +ssh-rsa

ssh_keys: []
ssh_keys_remove: []
