# roles/env/tasks/install.yml
---
- name: Create Google credentials directory
  ansible.builtin.file:
    dest: "{{ env_google_credentials_dir }}"
    mode: 0755
    state: directory

- name: Add Google credentials
  ansible.builtin.copy:
    src: "{{ item.value }}"
    dest: "{{ env_google_credentials_dir }}/{{ item.value }}"
    mode: 0644
  loop: "{{ env_google | dict2items }}"
  loop_control:
    label: "{{ item.value }}"

- name: Add .env
  ansible.builtin.template:
    src: env.j2
    dest: "{{ env }}"
    mode: 0644

- name: Add .env.local
  ansible.builtin.copy:
    dest: "{{ env_local }}"
    mode: 0644
    force: no
    content: ""
