# roles/env/tasks/install.yml
---
- name: Clean abandoned env
  ansible.builtin.file:
    dest: "{{ item }}"
    state: absent
  loop: "{{ env_abandoned }}"

- name: Add .env
  ansible.builtin.template:
    src: env.j2
    dest: "{{ env }}"
    mode: 0644

- name: Add .env.local
  ansible.builtin.copy:
    dest: "{{ env_local }}"
    mode: 0644
    force: no
    content: ""
